#!/bin/bash

DEDIR=/home/synapse/Desktop/
BIN_DIR=/home/myelin/bin
LOG=$DEDIR/hook.log

student=`pwd | sed 's:.*/\(.*\)\.git:\1:'`
# on post-receive, this should be valid.  Verify
this_commit=`git rev-list --all -n 1`

#echo "commit: $this_commit" >> $LOG

python $BIN_DIR/notify.py $student $this_commit
